// ingredient_categories.dart

import 'package:recipe_app/classes/ingredient.dart';

String categoryForIngredient(Ingredient ing) {
  final text = [ing.item, ing.raw].whereType<String>().join(' ').toLowerCase();

  // Check in priority order - more specific categories first
  if (_spicesAndSeasonings.any(text.contains)) return 'Spices & Seasonings';
  if (_oils.any(text.contains)) return 'Oils & Vinegars';
  if (_dairyAndCheese.any(text.contains)) return 'Dairy';
  if (_meatPoultryAndFish.any(text.contains)) return 'Meat, Poultry & Fish';
  if (_freshProduce.any(text.contains)) return 'Produce';
  if (_grains.any(text.contains)) return 'Grains & Bread';
  if (_legumesAndNuts.any(text.contains)) return 'Legumes & Nuts';
  if (_frozenFoods.any(text.contains)) return 'Frozen Foods';
  if (_cannedAndJarred.any(text.contains)) return 'Canned & Jarred';
  if (_condimentsAndSauces.any(text.contains)) return 'Condiments & Sauces';
  if (_bakingSupplies.any(text.contains)) return 'Baking Supplies';
  if (_sweetenerAndSugar.any(text.contains)) return 'Sweeteners & Sugar';
  if (_beverages.any(text.contains)) return 'Beverages';
  if (_seafood.any(text.contains)) return 'Seafood';
  if (_fruitAndJuices.any(text.contains)) return 'Fruits & Juices';
  if (_herbsAndFlavorings.any(text.contains)) return 'Herbs & Flavorings';

  return 'Pantry';
}

// Spices & Seasonings - comprehensive list
const _spicesAndSeasonings = [
  'salt',
  'pepper',
  'paprika',
  'cumin',
  'coriander',
  'turmeric',
  'cinnamon',
  'nutmeg',
  'cloves',
  'allspice',
  'cardamom',
  'ginger',
  'cayenne',
  'chili',
  'mustard',
  'oregano',
  'basil',
  'thyme',
  'rosemary',
  'sage',
  'marjoram',
  'tarragon',
  'dill',
  'fennel',
  'anise',
  'saffron',
  'fenugreek',
  'asafoetida',
  'sumac',
  'za\'atar',
  'seven spice',
  'garam masala',
  'curry',
  'chinese five spice',
  'peppercorn',
  'juniper',
  'coriander seed',
  'cumin seed',
  'seasoning',
  'garlic powder',
  'onion powder',
  'smoked paprika',
  'chipotle',
  'red pepper flakes',
  'crushed red pepper',
];

// Oils & Vinegars
const _oils = [
  'olive oil',
  'vegetable oil',
  'canola oil',
  'coconut oil',
  'sesame oil',
  'peanut oil',
  'sunflower oil',
  'grapeseed oil',
  'walnut oil',
  'avocado oil',
  'macadamia oil',
  'truffle oil',
  'almond oil',
  'hazelnut oil',
  'corn oil',
  'safflower oil',
  'vinegar',
  'balsamic vinegar',
  'white vinegar',
  'apple cider vinegar',
  'rice vinegar',
  'wine vinegar',
  'red wine vinegar',
  'white wine vinegar',
  'malt vinegar',
  'sherry vinegar',
  'champagne vinegar',
];

// Dairy & Cheese - very detailed
const _dairyAndCheese = [
  'milk',
  'whole milk',
  'skim milk',
  'low-fat milk',
  'buttermilk',
  'cream',
  'heavy cream',
  'whipping cream',
  'sour cream',
  'crème fraîche',
  'greek yogurt',
  'yogurt',
  'butter',
  'ghee',
  'cheese',
  'cheddar',
  'mozzarella',
  'parmesan',
  'parmigiano',
  'brie',
  'camembert',
  'feta',
  'ricotta',
  'mascarpone',
  'gouda',
  'gruyère',
  'emmental',
  'swiss cheese',
  'blue cheese',
  'gorgonzola',
  'roquefort',
  'goat cheese',
  'chèvre',
  'halloumi',
  'provolone',
  'fontina',
  'asiago',
  'pecorino',
  'cotija',
  'queso',
  'cream cheese',
  'neufchâtel',
  'cottage cheese',
];

// Meat, Poultry & Fish - comprehensive
const _meatPoultryAndFish = [
  'chicken',
  'chicken breast',
  'chicken thighs',
  'chicken legs',
  'chicken wings',
  'ground chicken',
  'turkey',
  'ground turkey',
  'beef',
  'ground beef',
  'beef steak',
  'ribeye',
  'sirloin',
  'tenderloin',
  'chuck',
  'brisket',
  'short ribs',
  'pork',
  'ground pork',
  'pork chops',
  'pork tenderloin',
  'pork ribs',
  'bacon',
  'pancetta',
  'prosciutto',
  'ham',
  'lamb',
  'lamb chops',
  'lamb shoulder',
  'lamb leg',
  'ground lamb',
  'veal',
  'duck',
  'duck breast',
  'goose',
  'venison',
  'rabbit',
  'sausage',
  'chorizo',
  'andouille',
  'kielbasa',
  'bratwurst',
  'hotdog',
  'hot dog',
];

// Fresh Produce
const _freshProduce = [
  'onion',
  'red onion',
  'yellow onion',
  'white onion',
  'sweet onion',
  'garlic',
  'tomato',
  'cherry tomato',
  'heirloom tomato',
  'lettuce',
  'romaine',
  'iceberg',
  'arugula',
  'spinach',
  'kale',
  'chard',
  'collard',
  'mustard greens',
  'beet greens',
  'pepper',
  'bell pepper',
  'red pepper',
  'green pepper',
  'yellow pepper',
  'orange pepper',
  'hot pepper',
  'jalapeño',
  'serrano',
  'habanero',
  'carrot',
  'celery',
  'cucumber',
  'zucchini',
  'courgette',
  'summer squash',
  'winter squash',
  'butternut squash',
  'acorn squash',
  'aubergine',
  'eggplant',
  'broccoli',
  'cauliflower',
  'cabbage',
  'brussels sprouts',
  'brassica',
  'radish',
  'turnip',
  'parsnip',
  'potato',
  'sweet potato',
  'yam',
  'beet',
  'beetroot',
  'leek',
  'scallion',
  'green onion',
  'spring onion',
  'bok choy',
  'gai lan',
  'broccoli rabe',
  'rapini',
  'asparagus',
  'green beans',
  'snap peas',
  'snow peas',
  'mushroom',
  'shiitake',
  'portobello',
  'cremini',
  'oyster mushroom',
  'lemon',
  'lime',
  'orange',
  'grapefruit',
  'avocado',
  'corn',
  'pumpkin',
];

// Grains & Bread
const _grains = [
  'bread',
  'whole grain bread',
  'whole wheat bread',
  'sourdough',
  'rye bread',
  'flatbread',
  'pita',
  'naan',
  'tortilla',
  'wrap',
  'bun',
  'roll',
  'bagel',
  'croissant',
  'rice',
  'white rice',
  'brown rice',
  'jasmine rice',
  'basmati rice',
  'arborio rice',
  'risotto',
  'pasta',
  'spaghetti',
  'fettuccine',
  'penne',
  'rigatoni',
  'lasagna noodle',
  'couscous',
  'quinoa',
  'barley',
  'oats',
  'oatmeal',
  'cereal',
  'muesli',
  'granola',
  'millet',
  'farro',
  'bulgur',
  'buckwheat',
  'polenta',
  'cornmeal',
  'flour',
  'all-purpose flour',
  'bread flour',
  'cake flour',
  'whole wheat flour',
  'rye flour',
  'corn flour',
  'cornstarch',
];

// Legumes & Nuts
const _legumesAndNuts = [
  'bean',
  'black bean',
  'pinto bean',
  'kidney bean',
  'chickpea',
  'garbanzo',
  'lentil',
  'pea',
  'split pea',
  'peanut',
  'almond',
  'walnut',
  'cashew',
  'hazelnut',
  'macadamia',
  'pecan',
  'pistachio',
  'pine nut',
  'sunflower seed',
  'pumpkin seed',
  'sesame seed',
  'flax seed',
  'chia seed',
  'hemp seed',
  'quinoa seed',
];

// Frozen Foods
const _frozenFoods = [
  'frozen',
  'frozen vegetable',
  'frozen fruit',
  'frozen pea',
  'frozen carrot',
  'frozen broccoli',
  'frozen spinach',
  'frozen corn',
  'ice cream',
  'gelato',
  'sorbet',
  'frozen pizza',
  'frozen meal',
  'frozen fish',
  'frozen chicken',
];

// Canned & Jarred
const _cannedAndJarred = [
  'canned',
  'tinned',
  'jarred',
  'canned tomato',
  'tomato paste',
  'tomato sauce',
  'canned bean',
  'canned chickpea',
  'canned tuna',
  'canned salmon',
  'canned sardine',
  'canned vegetable',
  'canned corn',
  'canned pea',
  'canned carrot',
  'pickle',
  'pickled',
  'jam',
  'jelly',
  'preserves',
  'marmalade',
  'peanut butter',
  'almond butter',
  'tahini',
  'paste',
];

// Condiments & Sauces
const _condimentsAndSauces = [
  'ketchup',
  'mustard',
  'mayo',
  'mayonnaise',
  'aioli',
  'salsa',
  'guacamole',
  'hummus',
  'pesto',
  'chimichurri',
  'hot sauce',
  'worcestershire',
  'soy sauce',
  'tamari',
  'fish sauce',
  'oyster sauce',
  'hoisin sauce',
  'sriracha',
  'tabasco',
  'sauce',
  'gravy',
  'broth',
  'stock',
  'bouillon',
  'marinara',
  'bolognese',
  'alfredo',
  'barbecue sauce',
  'bbq sauce',
  'teriyaki',
  'sweet and sour',
  'ponzu',
  'dressing',
  'vinaigrette',
];

// Baking Supplies
const _bakingSupplies = [
  'baking powder',
  'baking soda',
  'yeast',
  'active dry yeast',
  'instant yeast',
  'leavening',
  'chocolate',
  'cocoa',
  'cocoa powder',
  'dark chocolate',
  'milk chocolate',
  'white chocolate',
  'chocolate chip',
  'vanilla extract',
  'almond extract',
  'peppermint extract',
  'extract',
  'emulsion',
  'cake mix',
  'brownie mix',
];

// Sweeteners & Sugar
const _sweetenerAndSugar = [
  'sugar',
  'white sugar',
  'granulated sugar',
  'brown sugar',
  'turbinado',
  'muscovado',
  'demerara',
  'honey',
  'agave',
  'maple syrup',
  'molasses',
  'corn syrup',
  'sweetener',
  'stevia',
  'artificial sweetener',
  'splenda',
  'truvia',
];

// Beverages
const _beverages = [
  'water',
  'juice',
  'orange juice',
  'apple juice',
  'cranberry juice',
  'lime juice',
  'lemon juice',
  'coffee',
  'espresso',
  'tea',
  'black tea',
  'green tea',
  'herbal tea',
  'milk',
  'smoothie',
  'alcohol',
  'wine',
  'beer',
  'vodka',
  'rum',
  'whiskey',
  'brandy',
  'liqueur',
  'champagne',
  'prosecco',
  'cider',
];

// Seafood - detailed
const _seafood = [
  'fish',
  'salmon',
  'tuna',
  'cod',
  'halibut',
  'flounder',
  'sole',
  'sea bass',
  'tilapia',
  'snapper',
  'swordfish',
  'mahi mahi',
  'mackerel',
  'sardine',
  'anchovie',
  'anchovy',
  'shrimp',
  'prawn',
  'crab',
  'lobster',
  'scallop',
  'mussel',
  'clam',
  'oyster',
  'squid',
  'octopus',
  'calamari',
];

// Fruits & Juices
const _fruitAndJuices = [
  'apple',
  'banana',
  'orange',
  'lemon',
  'lime',
  'grapefruit',
  'strawberry',
  'raspberry',
  'blueberry',
  'blackberry',
  'grape',
  'kiwi',
  'mango',
  'pineapple',
  'papaya',
  'coconut',
  'melon',
  'cantaloupe',
  'honeydew',
  'watermelon',
  'peach',
  'pear',
  'plum',
  'cherry',
  'cranberry',
  'pomegranate',
  'fig',
  'date',
  'raisin',
  'dried fruit',
  'apricot',
  'prune',
];

// Herbs & Flavorings
const _herbsAndFlavorings = [
  'herb',
  'mint',
  'parsley',
  'cilantro',
  'coriander leaf',
  'dill',
  'chives',
  'basil',
  'oregano',
  'thyme',
  'rosemary',
  'sage',
  'tarragon',
  'marjoram',
  'bay leaf',
  'flavoring',
  'food coloring',
  'color',
];
